import type { WorkflowDefinition } from "./types";

export const DefaultWorkflowDefinitions: WorkflowDefinition[] = [
  {
    id: "direct-run",
    label: "Direct Run",
    description: "Route directly to a worker role without an explicit review step.",
    defaultForTaskTypes: ["planning"],
    steps: [
      {
        id: "plan",
        role: "planner",
        action: "plan",
        dependsOn: [],
        required: true,
        continueOnFailure: false,
      },
    ],
  },
  {
    id: "plan-build-review",
    label: "Plan, Build, Review",
    description: "General software or automation workflow with planner, builder, reviewer, and arbiter fallback.",
    defaultForTaskTypes: ["implementation"],
    steps: [
      {
        id: "plan",
        role: "planner",
        action: "plan",
        dependsOn: [],
        required: true,
        continueOnFailure: false,
      },
      {
        id: "build",
        role: "builder",
        action: "implement",
        dependsOn: ["plan"],
        required: true,
        continueOnFailure: false,
      },
      {
        id: "review",
        role: "reviewer",
        action: "review",
        dependsOn: ["build"],
        required: true,
        continueOnFailure: false,
      },
      {
        id: "arbitrate-if-blocked",
        role: "arbiter",
        action: "arbitrate",
        dependsOn: ["review"],
        required: false,
        continueOnFailure: true,
      },
    ],
  },
  {
    id: "plan-generate-review",
    label: "Plan, Generate, Review",
    description: "Content generation workflow for data, assets, writing, or game content.",
    defaultForTaskTypes: ["content"],
    steps: [
      {
        id: "plan",
        role: "planner",
        action: "plan",
        dependsOn: [],
        required: true,
        continueOnFailure: false,
      },
      {
        id: "generate",
        role: "generator",
        action: "generate-content",
        dependsOn: ["plan"],
        required: true,
        continueOnFailure: false,
      },
      {
        id: "review",
        role: "reviewer",
        action: "review",
        dependsOn: ["generate"],
        required: true,
        continueOnFailure: false,
      },
    ],
  },
  {
    id: "research-report",
    label: "Research Report",
    description: "Research, review, and summarize workflow for generic information tasks.",
    defaultForTaskTypes: [],
    steps: [
      {
        id: "research",
        role: "researcher",
        action: "research",
        dependsOn: [],
        required: true,
        continueOnFailure: false,
      },
      {
        id: "review",
        role: "reviewer",
        action: "review",
        dependsOn: ["research"],
        required: true,
        continueOnFailure: false,
      },
      {
        id: "summarize",
        role: "planner",
        action: "summarize",
        dependsOn: ["review"],
        required: true,
        continueOnFailure: false,
      },
    ],
  },
];
