import type { RoleDefinition } from "./types";

export const DefaultRoleDefinitions: RoleDefinition[] = [
  {
    id: "planner",
    label: "Planner",
    legacyRole: "director",
    provider: "claude-code",
    command: "claude",
    capabilities: ["plan", "review"],
    permissions: {
      canWriteFiles: false,
      canRunCommands: false,
      canRunTests: false,
      canReview: true,
      canArbitrate: false,
      canCreateTasks: true,
      requiresReview: false,
    },
  },
  {
    id: "builder",
    label: "Builder",
    legacyRole: "builder",
    provider: "codex",
    command: "codex",
    capabilities: ["implement", "run-tests", "write-files"],
    permissions: {
      canWriteFiles: true,
      canRunCommands: true,
      canRunTests: true,
      canReview: false,
      canArbitrate: false,
      canCreateTasks: false,
      requiresReview: true,
    },
  },
  {
    id: "generator",
    label: "Generator",
    legacyRole: "factory",
    provider: "ollama",
    model: "gemma",
    capabilities: ["generate-content"],
    permissions: {
      canWriteFiles: false,
      canRunCommands: false,
      canRunTests: false,
      canReview: false,
      canArbitrate: false,
      canCreateTasks: false,
      requiresReview: true,
    },
  },
  {
    id: "reviewer",
    label: "Reviewer",
    legacyRole: "director",
    provider: "claude-code",
    command: "claude",
    capabilities: ["review"],
    permissions: {
      canWriteFiles: false,
      canRunCommands: false,
      canRunTests: false,
      canReview: true,
      canArbitrate: false,
      canCreateTasks: false,
      requiresReview: false,
    },
  },
  {
    id: "arbiter",
    label: "Arbiter",
    legacyRole: "director",
    provider: "claude-code",
    command: "claude",
    capabilities: ["arbitrate", "review"],
    permissions: {
      canWriteFiles: false,
      canRunCommands: false,
      canRunTests: false,
      canReview: true,
      canArbitrate: true,
      canCreateTasks: true,
      requiresReview: false,
    },
  },
];

export const DefaultRoleAliases: Record<string, string> = {
  director: "planner",
  planner: "planner",
  coordinator: "planner",
  builder: "builder",
  worker: "builder",
  factory: "generator",
  generator: "generator",
  reviewer: "reviewer",
  arbiter: "arbiter",
};
