export function renderOfficeHtml(): string {
  return `<!doctype html>
<html lang="ko">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>AgentRunner Office</title>
  <style>
    :root{color-scheme:dark;--bg:#07111f;--panel:#101a2a;--panel2:#162337;--line:#2a3e5c;--text:#eaf1ff;--muted:#9fb0c8;--accent:#92d3ff;--bad:#ff9b9b;--ok:#9ff0b6;--warn:#f7d774}
    *{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at 10% 0%,#1e3457 0,transparent 34%),radial-gradient(circle at 88% 12%,rgba(146,211,255,.12),transparent 32%),var(--bg);color:var(--text);font-family:ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}a{color:var(--accent)}
    .shell{display:grid;grid-template-columns:minmax(780px,1fr)400px;gap:16px;min-height:100vh;padding:16px}header,.card{border:1px solid var(--line);border-radius:20px;background:rgba(16,26,42,.94);box-shadow:0 18px 50px rgba(0,0,0,.28)}header{grid-column:1/-1;display:flex;justify-content:space-between;align-items:flex-start;gap:14px;padding:16px 18px}h1,h2,p{margin:0}h1{font-size:24px;letter-spacing:-.02em}h2{font-size:15px;margin-bottom:10px}.muted{color:var(--muted)}.links{display:flex;flex-wrap:wrap;gap:8px;justify-content:flex-end}.pill{border:1px solid var(--line);border-radius:999px;padding:6px 10px;background:rgba(255,255,255,.04);color:var(--muted);text-decoration:none;font-size:12px}.canvasWrap{padding:14px;position:relative;overflow:hidden}.canvasWrap:before{content:"";position:absolute;inset:14px;border-radius:18px;pointer-events:none;box-shadow:inset 0 0 90px rgba(0,0,0,.42),inset 0 0 18px rgba(146,211,255,.08);z-index:2}canvas{width:100%;aspect-ratio:16/9;border:1px solid var(--line);border-radius:18px;background:#142137;image-rendering:pixelated;display:block}.legend{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.legend span{font-size:11px;border:1px solid var(--line);border-radius:999px;padding:4px 8px;color:var(--muted);background:rgba(255,255,255,.035)}.toolbar{display:flex;gap:8px;margin-bottom:12px}.toolbar input,.toolbar select{width:100%;border:1px solid var(--line);border-radius:12px;padding:9px;background:var(--panel2);color:var(--text)}.side{display:flex;flex-direction:column;min-height:0}.panel{padding:14px;border-bottom:1px solid var(--line)}.stats{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.stat,.row{border:1px solid var(--line);border-radius:14px;background:var(--panel2);padding:10px}.row{cursor:pointer}.row:hover{border-color:var(--accent);background:#1b2a42}.stat strong{display:block;font-size:26px;margin-top:4px}.list{display:grid;gap:8px;max-height:250px;overflow:auto}.rowTop{display:flex;justify-content:space-between;gap:8px}.title{font-weight:800;font-size:13px;overflow:hidden;white-space:nowrap;text-overflow:ellipsis}.sub{color:var(--muted);font-size:12px;overflow:hidden;white-space:nowrap;text-overflow:ellipsis}.badge{border-radius:999px;padding:2px 8px;font-size:11px;color:var(--muted);background:#26364d}.badge.ok{color:var(--ok);background:#15331f}.badge.warn{color:var(--warn);background:#392f12}.badge.bad{color:var(--bad);background:#421b1b}.detail{font-size:12px;color:var(--muted);line-height:1.55}.detail code{color:var(--text)}@media(max-width:1120px){.shell{grid-template-columns:1fr}}
  </style>
</head>
<body>
  <main class="shell">
    <header>
      <div><h1>AgentRunner Office</h1><p class="muted">Discord는 대화/명령/승인, 이 화면은 AgentRunner 작업 상태를 DeskRPG 스타일의 가상 오피스로 보여줍니다.</p></div>
      <nav class="links"><span class="pill" id="connection">connecting</span><a class="pill" href="/api/office/scene">scene</a><a class="pill" href="/api/office/snapshot">snapshot</a><a class="pill" href="/api/office/bridge">bridge</a><a class="pill" href="/health">health</a></nav>
    </header>
    <section class="card canvasWrap"><canvas id="office" width="960" height="540" aria-label="AgentRunner virtual pixel office"></canvas><div class="legend"><span>Planning</span><span>Review</span><span>Design</span><span>Builder</span><span>Factory</span><span>Attention</span><span>Done</span></div></section>
    <aside class="card side">
      <section class="panel"><h2>Runtime Summary</h2><div class="stats" id="stats"></div></section>
      <section class="panel"><h2>Agents</h2><div class="list" id="agents"></div></section>
      <section class="panel"><h2>Tasks</h2><div class="toolbar"><input id="search" placeholder="Search tasks" /><select id="statusFilter"><option value="">All</option><option value="attention">Attention</option><option value="open">Open</option><option value="done">Done</option></select></div><div class="list" id="tasks"></div></section>
      <section class="panel"><h2>Selected</h2><div class="detail" id="detail">작업을 선택하면 상세가 표시됩니다.</div></section>
      <section class="panel"><h2>Live Log</h2><div class="list" id="logs"></div></section>
    </aside>
  </main>
<script>
const canvas=document.getElementById('office'),ctx=canvas.getContext('2d'),statsEl=document.getElementById('stats'),agentsEl=document.getElementById('agents'),tasksEl=document.getElementById('tasks'),logsEl=document.getElementById('logs'),detailEl=document.getElementById('detail'),connectionEl=document.getElementById('connection'),searchEl=document.getElementById('search'),statusFilterEl=document.getElementById('statusFilter');let scene={width:960,height:540,tile:32,rooms:[],furniture:[],palette:{floor:'#142137',wall:'#263a58',grid:'rgba(255,255,255,.055)',desk:'#8b6b4a',deskTop:'#b98b5f',board:'#244d59',rack:'#222b3e',plant:'#70d68c',rug:'rgba(146,211,255,.13)',glow:'rgba(146,211,255,.28)'}};let snapshot={totals:{tasks:0,openTasks:0,blockedTasks:0,approvedTasks:0},zones:[],agents:[],tasks:[],logs:[]};let selectedTaskId='';const sprites=new Map();
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c])}function badgeClass(s){if(['approved','completed'].includes(s))return'ok';if(['blocked','failed','needs_human','split_task','retry_with_different_agent'].includes(s))return'bad';if(['pending','running','needs_revision'].includes(s))return'warn';return''}function isAttention(s){return ['blocked','failed','needs_human','split_task','retry_with_different_agent'].includes(s)}function isDone(s){return ['approved','completed'].includes(s)}
function row(title,status,sub,id){return '<div class="row" data-id="'+esc(id||'')+'"><div class="rowTop"><span class="title">'+esc(title)+'</span><span class="badge '+badgeClass(status)+'">'+esc(status)+'</span></div><div class="sub">'+esc(sub)+'</div></div>'}
function filteredTasks(){const query=searchEl.value.toLowerCase().trim();const filter=statusFilterEl.value;return (snapshot.tasks||[]).filter(t=>{const hay=(t.id+' '+t.title+' '+t.role+' '+t.status).toLowerCase();if(query&&!hay.includes(query))return false;if(filter==='attention')return isAttention(t.status);if(filter==='open')return !isDone(t.status);if(filter==='done')return isDone(t.status);return true}).slice(0,30)}
function renderSidePanel(){const totals=snapshot.totals||{tasks:0,openTasks:0,blockedTasks:0,approvedTasks:0};statsEl.innerHTML=[['Total',totals.tasks],['Open',totals.openTasks],['Blocked',totals.blockedTasks],['Approved',totals.approvedTasks]].map(p=>'<div class="stat"><span class="muted">'+p[0]+'</span><strong>'+p[1]+'</strong></div>').join('');agentsEl.innerHTML=(snapshot.agents||[]).map(a=>row(a.name,a.status,a.taskId?a.taskId+' · '+a.taskTitle:'idle',a.taskId)).join('')||'<div class="row muted">No agents yet.</div>';tasksEl.innerHTML=filteredTasks().map(t=>row(t.id,t.status,t.role+' · '+t.title,t.id)).join('')||'<div class="row muted">No matching tasks.</div>';logsEl.innerHTML=(snapshot.logs||[]).map(l=>row(l.label,l.status,l.createdAt,l.id)).join('')||'<div class="row muted">No task events yet.</div>';renderDetail()}
function renderDetail(){const task=(snapshot.tasks||[]).find(t=>t.id===selectedTaskId);const agent=(snapshot.agents||[]).find(a=>a.taskId===selectedTaskId);if(!task){detailEl.textContent='작업을 선택하면 상세가 표시됩니다.';return}detailEl.innerHTML='<p><code>'+esc(task.id)+'</code></p><p><strong>'+esc(task.title)+'</strong></p><p>Status: '+esc(task.status)+'</p><p>Role: '+esc(task.role)+'</p><p>Zone: '+esc(task.zoneId)+'</p><p>Updated: '+esc(task.updatedAt)+'</p>'+(agent?'<p>Agent: '+esc(agent.name)+' · '+esc(agent.message)+'</p>':'')+'<p><a href="'+esc(task.href)+'">Open JSON detail</a></p>'}
function roomById(id){return (scene.rooms||[]).find(r=>r.id===id)}function roomTaskCount(id){return (snapshot.tasks||[]).filter(t=>t.zoneId===id&&!isDone(t.status)).length}function roleColor(a){if(a.color==='gold')return'#ffd166';if(a.color==='green')return'#9ff0b6';if(a.color==='pink')return'#ffb3d1';return'#95d5ff'}function statusIcon(status){if(isAttention(status))return'!';if(isDone(status))return'✓';if(['pending','running','needs_revision'].includes(status))return'…';return''}
function drawRect(x,y,w,h,fill,stroke){ctx.fillStyle=fill;ctx.fillRect(x,y,w,h);if(stroke){ctx.strokeStyle=stroke;ctx.strokeRect(x+.5,y+.5,w-1,h-1)}}function drawLabel(text,x,y,color){ctx.fillStyle=color||'#9fb0c8';ctx.font='13px monospace';ctx.textAlign='left';ctx.fillText(text,x,y)}
function drawFloor(){ctx.fillStyle=scene.palette.floor||'#142137';ctx.fillRect(0,0,canvas.width,canvas.height);const tile=scene.tile||32;for(let y=0;y<canvas.height;y+=tile){for(let x=0;x<canvas.width;x+=tile){ctx.fillStyle=((x/tile+y/tile)%2===0)?'rgba(255,255,255,.018)':'rgba(0,0,0,.02)';ctx.fillRect(x,y,tile,tile)}}ctx.strokeStyle=scene.palette.grid||'rgba(255,255,255,.05)';for(let x=0;x<canvas.width;x+=tile){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,canvas.height);ctx.stroke()}for(let y=0;y<canvas.height;y+=tile){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(canvas.width,y);ctx.stroke()}}
function drawLight(x,y,r,color){const g=ctx.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,color);g.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=g;ctx.fillRect(x-r,y-r,r*2,r*2)}
function drawAmbientLights(){drawLight(160,120,150,'rgba(255,209,102,.12)');drawLight(480,310,170,'rgba(112,214,140,.10)');drawLight(730,130,150,'rgba(255,179,209,.10)');drawLight(460,470,120,'rgba(255,155,155,.10)')}
function drawRooms(){for(const r of scene.rooms||[]){const active=roomTaskCount(r.id);drawRect(r.x+4,r.y+4,r.w,r.h,'rgba(0,0,0,.15)');drawRect(r.x,r.y,r.w,r.h,active?'rgba(146,211,255,.075)':'rgba(255,255,255,.04)','rgba(146,211,255,.34)');drawRect(r.x,r.y,r.w,8,'rgba(255,255,255,.06)');drawLabel(r.label,r.x+10,r.y+22,active?'#eaf1ff':'#9fb0c8');if(active){ctx.fillStyle='rgba(247,215,116,.9)';ctx.fillRect(r.x+r.w-26,r.y+10,16,16);ctx.fillStyle='#07111f';ctx.textAlign='center';ctx.font='11px monospace';ctx.fillText(String(active),r.x+r.w-18,r.y+22)}}}
function drawFurniture(){for(const f of scene.furniture||[]){const p=scene.palette;ctx.fillStyle='rgba(0,0,0,.20)';ctx.fillRect(f.x+4,f.y+5,f.w,f.h);switch(f.kind){case'desk':drawRect(f.x,f.y,f.w,f.h,p.desk||'#8b6b4a','#d3a36d');drawRect(f.x+8,f.y+8,f.w-16,8,p.deskTop||'#b98b5f');ctx.fillStyle='#111827';ctx.fillRect(f.x+18,f.y+20,18,12);ctx.fillStyle='#92d3ff';ctx.fillRect(f.x+21,f.y+22,12,6);break;case'table':drawRect(f.x,f.y,f.w,f.h,'#73533d','#b98b5f');ctx.fillStyle='rgba(255,255,255,.14)';ctx.fillRect(f.x+10,f.y+8,f.w-20,7);break;case'board':drawRect(f.x,f.y,f.w,f.h,p.board||'#244d59','#92d3ff');ctx.fillStyle='rgba(255,255,255,.25)';ctx.fillRect(f.x+8,f.y+8,f.w-16,3);ctx.fillRect(f.x+8,f.y+16,f.w*.55,3);break;case'rack':drawRect(f.x,f.y,f.w,f.h,p.rack||'#222b3e','#647896');for(let y=f.y+10;y<f.y+f.h;y+=16){ctx.strokeStyle='#647896';ctx.beginPath();ctx.moveTo(f.x+3,y);ctx.lineTo(f.x+f.w-3,y);ctx.stroke()}break;case'sofa':drawRect(f.x,f.y,f.w,f.h,'#374464','#8aa0c2');drawRect(f.x+8,f.y-8,f.w-16,14,'#425374','#8aa0c2');break;case'plant':ctx.fillStyle=p.plant||'#70d68c';ctx.fillRect(f.x+8,f.y,8,24);ctx.fillRect(f.x+2,f.y+8,20,12);ctx.fillRect(f.x+12,f.y+6,14,14);ctx.fillStyle='#8b6b4a';ctx.fillRect(f.x+5,f.y+26,14,16);break;case'screen':drawRect(f.x,f.y,f.w,f.h,'#08111f','#92d3ff');ctx.fillStyle='rgba(146,211,255,.38)';ctx.fillRect(f.x+8,f.y+8,f.w-16,f.h-16);drawLight(f.x+f.w/2,f.y+f.h/2,48,scene.palette.glow||'rgba(146,211,255,.2)');break;case'terminal':drawRect(f.x,f.y,f.w,f.h,'#07111f','#70d68c');ctx.fillStyle='#70d68c';ctx.font='11px monospace';ctx.fillText('> run',f.x+10,f.y+20);ctx.fillText('ok',f.x+10,f.y+31);break;case'coffee':drawRect(f.x,f.y,f.w,f.h,'#5e3d2b','#b98b5f');ctx.fillStyle='#eaf1ff';ctx.fillRect(f.x+12,f.y+10,12,10);ctx.fillStyle='#92d3ff';ctx.fillRect(f.x+34,f.y+11,54,7);break;case'rug':drawRect(f.x,f.y,f.w,f.h,p.rug||'rgba(146,211,255,.13)','rgba(146,211,255,.22)');break}if(f.label){drawLabel(f.label,f.x+6,f.y+f.h-8,'rgba(234,241,255,.72)')}}}
function targetForAgent(agent){const room=roomById(agent.zoneId);if(room){const idx=(snapshot.agents||[]).filter(a=>a.zoneId===agent.zoneId).findIndex(a=>a.id===agent.id);return{x:room.x+46+(idx%4)*44,y:room.y+64+Math.floor(idx/4)*42}}return{x:agent.x*9.6,y:agent.y*5.4}}
function updateSprite(agent){const target=targetForAgent(agent);let s=sprites.get(agent.id);if(!s){s={x:target.x,y:target.y,tx:target.x,ty:target.y,step:0};sprites.set(agent.id,s)}s.tx=target.x;s.ty=target.y;s.x+=(s.tx-s.x)*0.12;s.y+=(s.ty-s.y)*0.12;s.step+=Math.abs(s.tx-s.x)+Math.abs(s.ty-s.y)>1?0.18:0.04;return s}
function drawBubble(a,s){ctx.fillStyle='rgba(4,8,16,.80)';ctx.fillRect(s.x-54,s.y-66,108,32);ctx.strokeStyle='#314866';ctx.strokeRect(s.x-54,s.y-66,108,32);ctx.fillStyle='#eaf1ff';ctx.font='11px monospace';ctx.textAlign='center';ctx.fillText(String(a.message||a.status).slice(0,17),s.x,s.y-46)}
function drawPixelAgent(a){const s=updateSprite(a);drawBubble(a,s);const bob=Math.sin(s.step)*2,leg=Math.sin(s.step)*3,x=s.x,y=s.y+bob;ctx.fillStyle='rgba(0,0,0,.28)';ctx.beginPath();ctx.ellipse(x,y+28,20,6,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#2a1d18';ctx.fillRect(x-10,y-30,20,8);ctx.fillStyle='#f7cfa2';ctx.fillRect(x-9,y-24,18,14);ctx.fillStyle=roleColor(a);ctx.fillRect(x-14,y-10,28,25);ctx.fillStyle='#fff';ctx.fillRect(x-14,y+1,28,5);ctx.fillStyle='#1f3150';ctx.fillRect(x-11,y+15+leg,8,10);ctx.fillRect(x+3,y+15-leg,8,10);ctx.fillStyle='#0b1020';ctx.fillRect(x-5,y-19,3,3);ctx.fillRect(x+4,y-19,3,3);ctx.fillStyle=roleColor(a);ctx.fillRect(x-18,y-7,5,15);ctx.fillRect(x+13,y-7,5,15);const icon=statusIcon(a.status);if(icon){ctx.fillStyle=isAttention(a.status)?'#ff9b9b':'#9ff0b6';ctx.font='bold 16px monospace';ctx.fillText(icon,x+20,y-18)}ctx.fillStyle='#eaf1ff';ctx.font='12px monospace';ctx.textAlign='center';ctx.fillText(a.name,x,y+44)}
function drawOffice(){drawFloor();drawAmbientLights();drawRooms();drawFurniture();for(const a of snapshot.agents||[])drawPixelAgent(a)}function animate(){drawOffice();requestAnimationFrame(animate)}
function render(){renderSidePanel()}async function sync(){try{const response=await fetch('/api/office/bridge',{cache:'no-store'});const payload=await response.json();snapshot=payload.snapshot||snapshot;connectionEl.textContent='live';render()}catch(e){connectionEl.textContent='error'}}async function loadScene(){try{const response=await fetch('/api/office/scene',{cache:'no-store'});scene=await response.json()}catch(e){connectionEl.textContent='scene fallback'}}
[searchEl,statusFilterEl].forEach(el=>el.addEventListener('input',renderSidePanel));document.body.addEventListener('click',e=>{const item=e.target.closest('.row[data-id]');if(item&&item.dataset.id){selectedTaskId=item.dataset.id;renderDetail()}});loadScene().then(sync);animate();const events=new EventSource('/api/office/events');events.addEventListener('snapshot',sync);events.onerror=()=>{connectionEl.textContent='reconnecting'};setInterval(sync,5000);
</script></body></html>`;
}
