import { z } from "zod";

const OptionalWorkerRoleSchema = z.preprocess(
  (value) => value === "" ? undefined : value,
  z.enum(["director", "builder", "factory", "designer"]).optional(),
);

const StartupRecoveryModeSchema = z.preprocess(
  (value) => value === "" ? undefined : value,
  z.enum(["requeue", "block"]).default("requeue"),
);

const ConfigSchema = z.object({
  DIRECTOR_DISCORD_TOKEN: z.string().optional().default(""),
  BUILDER_DISCORD_TOKEN: z.string().optional().default(""),
  FACTORY_DISCORD_TOKEN: z.string().optional().default(""),
  DESIGNER_DISCORD_TOKEN: z.string().optional().default(""),
  DISCORD_CLIENT_ID: z.string().optional().default(""),
  DISCORD_GUILD_ID: z.string().optional().default(""),
  REGISTER_SLASH_COMMANDS: z.coerce.boolean().default(false),
  GAME_DIRECTOR_CHANNEL_ID: z.string().optional().default(""),
  DEV_TASKS_CHANNEL_ID: z.string().optional().default(""),
  CONTENT_FACTORY_CHANNEL_ID: z.string().optional().default(""),
  DESIGN_TASKS_CHANNEL_ID: z.string().optional().default(""),
  REVIEW_LOG_CHANNEL_ID: z.string().optional().default(""),
  BUILD_LOG_CHANNEL_ID: z.string().optional().default(""),
  DATABASE_PATH: z.string().default("./data/agentrunner.sqlite"),
  OBSIDIAN_VAULT_PATH: z.string().default("./vault/AgentRunnerVault"),
  PROJECT_ROOT: z.string().default("./game-project"),
  GROUPS_CONFIG_PATH: z.string().optional().default("./configs/groups.yaml"),
  ROLES_CONFIG_PATH: z.string().optional().default("./configs/roles.yaml"),
  WORKFLOWS_CONFIG_PATH: z.string().optional().default("./configs/workflows.yaml"),
  SKILLS_DIR: z.string().optional().default("./skills"),
  ATTACHMENTS_DIR: z.string().optional().default("./data/attachments"),
  DESIGNER_OUTPUT_DIR: z.string().optional().default("./vault/AgentRunnerVault/06_DesignerOutputs"),
  MAX_ATTACHMENT_BYTES: z.coerce.number().int().positive().default(10_000_000),
  DASHBOARD_ENABLED: z.coerce.boolean().default(false),
  DASHBOARD_HOST: z.string().default("127.0.0.1"),
  DASHBOARD_PORT: z.coerce.number().int().positive().default(8787),
  VISION_COMMAND: z.string().optional().default(""),
  VISION_COMMAND_TIMEOUT_MS: z.coerce.number().int().positive().default(300000),
  BROWSER_COMMAND: z.string().optional().default(""),
  BROWSER_COMMAND_TIMEOUT_MS: z.coerce.number().int().positive().default(300000),
  ENABLE_AGENT_FAILOVER: z.coerce.boolean().default(true),
  CLAUDE_CODE_COMMAND: z.string().default("claude"),
  CLAUDE_CODE_COMMANDS: z.string().optional().default(""),
  CODEX_COMMAND: z.string().default("codex"),
  CODEX_COMMANDS: z.string().optional().default(""),
  FACTORY_COMMANDS: z.string().optional().default(""),
  OLLAMA_BASE_URL: z.string().url().default("http://localhost:11434/v1"),
  OLLAMA_BASE_URLS: z.string().optional().default(""),
  OLLAMA_MODEL: z.string().default("gemma"),
  OLLAMA_MODELS: z.string().optional().default(""),
  GEMINI_API_KEY: z.string().optional().default(""),
  GEMINI_IMAGE_MODEL: z.string().optional().default("gemini-3.1-flash-image-preview"),
  AI_COMMAND_TIMEOUT_MS: z.coerce.number().int().positive().default(600000),
  MAX_REVIEW_ROUNDS: z.coerce.number().int().positive().default(3),
  TASK_LEASE_MINUTES: z.coerce.number().int().positive().default(30),
  RECOVER_STALE_TASKS_ON_START: z.coerce.boolean().default(true),
  STARTUP_RECOVERY_MODE: StartupRecoveryModeSchema,
  STALE_TASK_MINUTES: z.coerce.number().int().positive().default(120),
  WORKER_HEARTBEAT_INTERVAL_MS: z.coerce.number().int().positive().default(30000),
  BUILDER_TEST_COMMAND: z.string().optional().default(""),
  BUILDER_BUILD_COMMAND: z.string().optional().default(""),
  BUILDER_DIFF_COMMAND: z.string().optional().default("git diff --stat && git diff --name-only"),
  REVIEW_READ_ONLY_GUARD: z.coerce.boolean().default(true),
  REVIEW_DIFF_COMMAND: z.string().optional().default("git diff --stat && git diff --name-only && git diff --check"),
  REVIEW_CONTEXT_COMMAND_TIMEOUT_MS: z.coerce.number().int().positive().default(120000),
  STRICT_REVIEW_ENABLED: z.coerce.boolean().default(true),
  STRICT_REVIEW_REQUIRE_TESTS: z.coerce.boolean().default(true),
  STRICT_REVIEW_COMMANDS: z.string().optional().default(""),
  STRICT_REVIEW_COMMAND_TIMEOUT_MS: z.coerce.number().int().positive().default(300000),
  STRICT_REVIEW_FAIL_ON_VALIDATION_ERROR: z.coerce.boolean().default(true),
  STRICT_REVIEW_BLOCK_LOCKFILE_CHANGES: z.coerce.boolean().default(false),
  APPROVED_TASK_COMMAND: z.string().optional().default(""),
  APPROVED_TASK_COMMAND_TIMEOUT_MS: z.coerce.number().int().positive().default(600000),
  REQUIRE_USER_APPROVAL_BEFORE_COMMIT: z.coerce.boolean().default(true),
  AGENTRUNNER_WORKER_ROLE: OptionalWorkerRoleSchema,
  WORKER_POLL_INTERVAL_MS: z.coerce.number().int().positive().default(5000),
  WORKER_POLL_ONCE: z.coerce.boolean().default(false),
  STEP_SCHEDULER_INTERVAL_MS: z.coerce.number().int().positive().default(5000),
  STEP_SCHEDULER_MAX_STEPS_PER_CYCLE: z.coerce.number().int().positive().default(20),
  STEP_SCHEDULER_ONCE: z.coerce.boolean().default(false),
});

export type RuntimeConfig = z.infer<typeof ConfigSchema>;

export function loadConfig(env: NodeJS.ProcessEnv = process.env): RuntimeConfig {
  return ConfigSchema.parse(env);
}
